{{- $prefectVolume := "prefect-credentials" -}}
{{- $gcpVolume := "google-application-credentials" -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.agent.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ .Values.agent.component }}
spec:
  replicas: {{ .Values.agent.autoscaling.minReplicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ .Values.agent.component }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ .Values.agent.component }}
    spec:
      serviceAccountName: {{ .Values.agent.serviceAccountName }}
      imagePullSecrets:
        - name: {{ .Values.secrets.ghcr.name }}
      containers:
        - name: flow
          image: "{{ .Values.agent.imageName }}:{{ .Chart.AppVersion }}"
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.infisical.name }}
          command:
            - bash
            - "-c"
          {{- if eq .Values.agent.type "vertex" }}
            {{- if .Values.agent.vertexServiceAccount }}
            - "prefect agent vertex start --region-name {{ .Values.agent.vertexRegion }} --service-account {{ .Values.agent.vertexServiceAccount }}"
            {{- else }}
            - "prefect agent vertex start --region-name {{ .Values.agent.vertexRegion }}"
            {{- end }}
          {{- else if eq .Values.agent.type "kubernetes" }}
            {{- if .Values.agent.jobTemplateFilePath }}
            - "prefect agent kubernetes start --job-template {{ .Values.agent.jobTemplateFilePath }}"
            {{- else }}
            - "prefect agent kubernetes start"
            {{- end }}
          {{- else }}
            - "echo 'Invalid agent type. Please set agent.type to either kubernetes or vertex.'"
          {{- end }}
          env:
            - name: PREFECT__CLOUD__API
              value: {{ .Values.agent.apolloUrl }}
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: PREFECT__CLOUD__AGENT__LABELS
              value: {{ .Values.agent.prefectLabels | toJson | quote }}
            - name: JOB_MEM_REQUEST
              value: {{ .Values.job.resources.requests.memory }}
            - name: JOB_MEM_LIMIT
              value: {{ .Values.job.resources.limits.memory }}
            - name: JOB_CPU_REQUEST
              value: {{ .Values.job.resources.requests.cpu }}
            - name: JOB_CPU_LIMIT
              value: {{ .Values.job.resources.limits.cpu }}
            - name: SERVICE_ACCOUNT_NAME
              value: {{ .Values.agent.serviceAccountName }}
            - name: PREFECT__CLOUD__AGENT__AGENT_ADDRESS
              value: http://0.0.0.0:8080
            {{- if .Values.agent.prefectBackendServer }}
            - name: PREFECT__BACKEND
              value: server
            {{- end }}
            {{- if eq .Values.agent.type "vertex" }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /root/.config/gcloud/creds.json
            {{- end }}
            {{- with .Values.agent.env }}
              {{- toYaml . | nindent 10 }}
            {{- end }}
          volumeMounts:
          {{- if .Values.secrets.prefect.name }}
            - name: {{ $prefectVolume }}
              mountPath: /root/.prefect/
              readOnly: true
          {{- end }}
          {{- if .Values.agent.gcpSASecretName }}
            - name: {{ $gcpVolume }}
              mountPath: /root/.config/gcloud/
              readOnly: true
          {{- end }}
          {{- if not .Values.secrets.prefect.name }}
            {{- if not .Values.agent.gcpSASecretName }}
            - name: empty-volume
              mountPath: /root/.prefect/
              emptyDir: {}
            {{- end }}
          {{- end }}
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 40
          {{- with .Values.agent.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
      {{- if .Values.secrets.prefect.name }}
        - name: {{ $prefectVolume }}
          secret:
            secretName: {{ .Values.secrets.prefect.name }}
      {{- end }}
      {{- if .Values.agent.gcpSASecretName }}
        - name: {{ $gcpVolume }}
          secret:
            secretName: {{ .Values.agent.gcpSASecretName }}
      {{- end }}
      {{- if not .Values.secrets.prefect.name }}
        {{- if not .Values.agent.gcpSASecretName }}
        - name: empty-volume
          emptyDir: {}
        {{- end }}
      {{- end }}
