apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.secrets.infisical.name }}
  namespace: {{ .Release.Namespace }}
data:
  INFISICAL_ADDRESS: {{ .Values.secrets.infisical.address }}
  INFISICAL_TOKEN: {{ .Values.secrets.infisical.token }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.agent.prefectAuthSecretName }}
  namespace: {{ .Release.Namespace }}
data:
  auth.toml: {{ .Values.secrets.prefect.authToml }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ .Values.secrets.ghcr.name }}
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ .Values.secrets.ghcr.dockerConfigJson }}
